trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
# ------------------------------------
# Stage 1: Build & Package
# ------------------------------------
- stage: Build
  displayName: 'Build and Package'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - script: |
        echo "Listing contents of $(build.artifactStagingDirectory):"
        dir "$(build.artifactStagingDirectory)"
      displayName: 'Debug: List output files'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        pathToPublish: '$(build.artifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: 'Container'

# ------------------------------------
# Stage 2: Deploy to Azure
# ------------------------------------
- stage: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Web App'
    pool:
      vmImage: 'windows-latest'
    steps:
    - download: current
      artifact: drop

    - task: AzureRmWebAppDeployment@5
      displayName: 'Deploy using Web Deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MSDN Platforms Subscription (6db4c0d0-c8ed-472b-8349-b3424a8af6ac)' # 🔁 Change to your connection
        appType: 'webApp'
        WebAppName: 'BlobApp21Jul25'                # 🔁 Change to your Azure Web App name
        package: '$(Pipeline.Workspace)/drop/**/*.zip'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'
