trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Optional debug step to verify ZIP file
- script: |
    echo "Build Artifact Directory:"
    dir "$(build.artifactStagingDirectory)"
  displayName: 'Debug: List build output'

# Deploy to Azure App Service (Windows)
- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MSDN Platforms Subscription (6db4c0d0-c8ed-472b-8349-b3424a8af6ac)' # Replace with your connection name
    appType: 'webApp'
    WebAppName: 'BlobApp21Jul25'               # Replace with your App Service name
    package: '$(build.artifactStagingDirectory)/**/*.zip'  # Correct for WebDeploy
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
